
NVDLA_FIRMWARE_DIR := $(NVDLA_SW_HOME)/kmd/firmware

FIRMWARE_INCLUDE_DIR := $(NVDLA_FIRMWARE_DIR)/include

FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/scheduler.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/engine.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/bdma.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/conv.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/sdp.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/cdp.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/pdp.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/rubik.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/cache.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/common.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/engine_data.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/engine_isr.c
FIRMWARE_SRCS += $(NVDLA_FIRMWARE_DIR)/engine_debug.c

